// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

/**
 * Vite inlines `import.meta.env.VITE_*` at build time, so these values are baked
 * into the deployed bundle. If the host project's environment variables are
 * missing on Vercel, the app would otherwise fail later with an opaque network
 * error (or send the browser to a deleted project), so fail loudly and early.
 */
const assertSupabaseConfig = () => {
  const problems: string[] = [];

  if (!SUPABASE_URL) {
    problems.push('VITE_SUPABASE_URL is not set');
  } else if (!/^https:\/\/[a-z0-9-]+\.supabase\.(co|in)$/.test(SUPABASE_URL)) {
    problems.push(`VITE_SUPABASE_URL is not a Supabase project URL (received "${SUPABASE_URL}")`);
  }

  if (!SUPABASE_PUBLISHABLE_KEY) {
    problems.push('VITE_SUPABASE_PUBLISHABLE_KEY is not set');
  }

  if (problems.length > 0) {
    throw new Error(
      `Supabase is not configured correctly: ${problems.join('; ')}. ` +
        'Set these as environment variables in your host (Vercel: Project Settings → Environment Variables) ' +
        'and redeploy — Vite inlines them at build time, so editing a local .env has no effect on the deployment.',
    );
  }
};

assertSupabaseConfig();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
